Repository JuliaData/DataFrames.jl, pull requests merged in 2019-12, with the labels that each got.

#1961 allow to create columns using : as row selector
  docs/src/lib/indexing.md
  src/dataframe/dataframe.jl
  src/other/broadcasting.jl
  test/broadcasting.jl
  test/indexing.jl
Labels: decision

#2047 Avoid computing group indices when possible
  src/abstractdataframe/reshape.jl
  src/dataframerow/utils.jl
  src/groupeddataframe/grouping.jl
  test/grouping.jl
Labels: grouping, performance

#2064 fix combine with DataFrameRow
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
Labels: bug
