Repository JuliaData/DataFrames.jl, pull requests merged in 2020-03, with the labels that each got.

#2128 [BREAKING] Change ArgumentError to DimensionMismatch
  src/dataframe/dataframe.jl
  src/other/index.jl
  src/other/utils.jl
  test/dataframe.jl
  test/index.jl
Labels: breaking

#2108 Add replacement examples to getting_started.md
  docs/src/man/getting_started.md
Labels: non-breaking

#2144 Make the Jupyter Notebook documentation more precise
  docs/src/man/getting_started.md
Labels: doc, non-breaking

#2141 add haskey to GroupedDataFrame and GroupKey
  src/groupeddataframe/groupeddataframe.jl
  test/grouping.jl
Labels: non-breaking

#2145 [BREAKING] fix eltype in stack with view=true
  src/abstractdataframe/reshape.jl
  test/reshape.jl
Labels: breaking

#2115 Show friendly error when trying to iterate DataFrames
  src/abstractdataframe/iteration.jl
  test/iteration.jl
Labels: non-breaking

#2140 change ⍰ to ? when showing a DataFrame with missing eltype
  docs/src/man/categorical.md
  docs/src/man/getting_started.md
  docs/src/man/joins.md
  docs/src/man/missing.md
  docs/src/man/reshaping_and_pivoting.md
  docs/src/man/sorting.md
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/join.jl
  src/abstractdataframe/show.jl
  src/dataframe/dataframe.jl
  test/io.jl
  test/show.jl
Labels: non-breaking

#2142 add displaycoltypes to showrows & show for dataframes
  src/abstractdataframe/io.jl
  src/abstractdataframe/show.jl
  test/io.jl
  test/show.jl
Labels: non-breaking

#2080 Add transformation and renaming to select and select!
  docs/src/lib/types.md
  docs/src/man/getting_started.md
  src/DataFrames.jl
  src/abstractdataframe/selection.jl
  src/dataframe/dataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/index.jl
  src/other/utils.jl
  src/subdataframe/subdataframe.jl
  test/dataframe.jl
  test/index.jl
  test/runtests.jl
  test/select.jl
Labels: non-breaking

#2160 update to Juia 1.4
  .travis.yml
  test/indexing.jl
  test/indexing_begin_tests.jl
  test/select.jl
Labels: non-breaking

#2147 [BREAKING] make id_vars go first in stack
  docs/src/man/reshaping_and_pivoting.md
  src/abstractdataframe/reshape.jl
  test/deprecated.jl
  test/reshape.jl
Labels: breaking
