Repository JuliaData/DataFrames.jl, pull requests merged in 2020-08, with the labels that each got.

#2341 Add check if input is a table before trying alternative constructors
  src/other/tables.jl
  test/tables.jl
Labels: backport, priority

#2339 remove median and nunique from describe by default
  src/abstractdataframe/abstractdataframe.jl
  test/dataframe.jl
Labels: breaking, performance

#2331 make colnames type stable in broadcasting
  src/other/broadcasting.jl
Labels: backport, bug, non-breaking

#2308 [BREAKING] make GroupKey API more consistent
  src/groupeddataframe/groupeddataframe.jl
  test/grouping.jl
Labels: breaking, feature, grouping

#2324 Handle zero groups
  src/abstractdataframe/io.jl
  src/abstractdataframe/selection.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/show.jl
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
Labels: breaking, bug, feature, grouping, priority

#2343 Update outdated documentation
  src/dataframerow/dataframerow.jl
  src/subdataframe/subdataframe.jl
Labels: backport, doc

#2349 fix locking of GroupedDataFrame
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/splitapplycombine.jl
Labels: backport, bug, grouping

#2345 Change Travis from Julia 1.4 to 1.5
  .travis.yml
  Project.toml
Labels: CI, backport, non-breaking

#2353 Update dataframerow.jl
  src/dataframerow/dataframerow.jl
Labels: backport, doc

#2350 Drop deprecations
  docs/src/index.md
  src/DataFrames.jl
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/join.jl
  src/abstractdataframe/selection.jl
  src/abstractdataframe/sort.jl
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
  src/deprecated.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/index.jl
  test/cat.jl
  test/constructors.jl
  test/dataframe.jl
  test/deprecated.jl
  test/grouping.jl
  test/index.jl
  test/indexing.jl
  test/join.jl
  test/sort.jl
Labels: non-breaking

#2313 implementation proposal of column renaming
  src/abstractdataframe/join.jl
  test/join.jl
Labels: feature, non-breaking

#2360 [BREAKING] Return 0 missing count for columns of nonmissing type
  src/abstractdataframe/abstractdataframe.jl
  test/dataframe.jl
Labels: breaking, feature

#2357 [BREAKING] fix isagg to correctly use a fast path
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
Labels: breaking, bug, priority

#2294 Update README.md with JuliaAcademy reference
  README.md
Labels: doc, non-breaking

#2356 add rownumber
  docs/src/lib/functions.md
  src/DataFrames.jl
  src/abstractdataframe/iteration.jl
  src/dataframerow/dataframerow.jl
  test/dataframerow.jl
Labels: feature, non-breaking

#2355 update contribution guidelines and add NEWS.md
  CONTRIBUTING.md
  NEWS.md
  README.md
Labels: backport, doc

#2368 better error for rename! and improved docstring
  src/abstractdataframe/abstractdataframe.jl
  src/other/index.jl
  test/dataframe.jl
Labels: feature, non-breaking

#2377 fix formatting of index.md in the manual
  docs/src/index.md
Labels: doc

#2380 add columnindex for DataFrameRow, speed up columnindex, fix a bug in indexing
  NEWS.md
  src/other/index.jl
  src/other/tables.jl
  test/indexing.jl
  test/tables.jl
Labels: bug, feature, non-breaking, performance

#2383 Don't match on AbstractVector type parameter due to compiler crash
  Project.toml
  src/groupeddataframe/splitapplycombine.jl
Labels: backport, bug, priority

#2281 Index to grouped data frame using `Dict`s
  NEWS.md
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
Labels: non-breaking

#2399 fix wrong docstring that was a leftover of changing the aggregation rules
  src/groupeddataframe/splitapplycombine.jl
Labels: doc

#2398 change kwarg rename to renamecols in joins
  NEWS.md
  src/abstractdataframe/join.jl
  test/join.jl
Labels: non-breaking

#2387 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: doc

#2391 [BREAKING] Change `stack` to create a `PooledArray{String}` column by default
  NEWS.md
  src/abstractdataframe/reshape.jl
  test/reshape.jl
Labels: breaking
