Repository JuliaData/DataFrames.jl, pull requests merged in 2020-05, with the labels that each got.

#2223 updates required for Julia 1.5
  src/other/broadcasting.jl
  test/data.jl
  test/show.jl
Labels: CI, non-breaking, priority

#2196 dataframerow related docstrings
  src/abstractdataframe/iteration.jl
  src/dataframerow/dataframerow.jl
  test/dataframerow.jl
Labels: breaking

#2214 [BREAKING] new design of select, transform and combine
  docs/src/man/getting_started.md
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/selection.jl
  src/dataframe/dataframe.jl
  src/deprecated.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  test/deprecated.jl
  test/grouping.jl
  test/select.jl
  test/string.jl
Labels: breaking, feature, grouping

#2231 Fix several references in documentation
  src/groupeddataframe/splitapplycombine.jl
Labels: doc

#2233 Fix docstring references in the manual
  docs/make.jl
  docs/src/lib/functions.md
  docs/src/lib/internals.md
  docs/src/lib/types.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/join.jl
  src/abstractdataframe/selection.jl
  src/abstractdataframe/show.jl
  src/groupeddataframe/splitapplycombine.jl
Labels: doc, priority

#2249 better deprecations of by and map
  src/deprecated.jl
  test/deprecated.jl
Labels: grouping, non-breaking

#2262 add empty and empty!
  docs/src/lib/functions.md
  src/abstractdataframe/abstractdataframe.jl
  src/dataframe/dataframe.jl
  src/deprecated.jl
  test/data.jl
  test/deprecated.jl
Labels: breaking

#2237 group functions by their roles in the manual
  docs/src/index.md
  docs/src/lib/functions.md
  docs/src/lib/types.md
Labels: doc
