Repository JuliaData/DataFrames.jl, pull requests merged in 2020-11, with the labels that each got.

#2505 [BREAKING] remove CategoricalArrays dependency from joins
  NEWS.md
  src/abstractdataframe/join.jl
Labels: breaking

#2481 [BREAKING] Multicolumn transformations for GoupedDataFrame
  NEWS.md
  docs/src/man/split_apply_combine.md
  src/DataFrames.jl
  src/abstractdataframe/selection.jl
  src/groupeddataframe/callprocessing.jl
  src/groupeddataframe/complextransforms.jl
  src/groupeddataframe/fastaggregates.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
  test/select.jl
  test/string.jl
Labels: breaking, grouping, priority

#2504 [BREAKING] add matchmissing kwarg to joins
  NEWS.md
  src/abstractdataframe/join.jl
  test/data.jl
  test/join.jl
Labels: breaking

#2514 require DataAPI.jl version 1.4
  NEWS.md
  Project.toml
Labels: ecosystem, non-breaking

#2511 fix deprecated tests in reshape
  test/reshape.jl
Labels: non-breaking

#2464 [BREAKING] deprecate DataFrame constructors
  NEWS.md
  Project.toml
  src/dataframe/dataframe.jl
  src/deprecated.jl
  src/other/tables.jl
  test/broadcasting.jl
  test/cat.jl
  test/constructors.jl
  test/data.jl
  test/dataframe.jl
  test/dataframerow.jl
  test/deprecated.jl
  test/grouping.jl
  test/indexing.jl
  test/indexing_begin_tests.jl
  test/io.jl
  test/iteration.jl
  test/reshape.jl
  test/select.jl
  test/show.jl
  test/sort.jl
  test/subdataframe.jl
  test/tables.jl
Labels: breaking

#2429 [BREAKING] Add PrettyTables.jl backend for printing DataFrames
  NEWS.md
  Project.toml
  src/DataFrames.jl
  src/abstractdataframe/io.jl
  src/abstractdataframe/iteration.jl
  src/abstractdataframe/prettytables.jl
  src/abstractdataframe/show.jl
  src/dataframerow/show.jl
  src/groupeddataframe/show.jl
  test/dataframerow.jl
  test/grouping.jl
  test/io.jl
  test/show.jl
Labels: breaking, display, priority

#2515 move All(args...) tests to deprecated.jl
  test/deprecated.jl
  test/index.jl
  test/string.jl
Labels: non-breaking

#2518 make hashrows_col! not depend on CategoricalArrays.jl
  src/dataframerow/utils.jl
  test/grouping.jl
Labels: ecosystem, non-breaking, performance

#2519 avoid CategoricalArrays dependency in aggregates
  src/groupeddataframe/fastaggregates.jl
  test/grouping.jl
Labels: grouping, non-breaking

#2523 Update Categorical test
  test/cat.jl
  test/dataframerow.jl
  test/grouping.jl
Labels: CI, ecosystem

#2456 Enable precompilation
  NEWS.md
  src/DataFrames.jl
  src/other/precompile.jl
  test/precompile.jl
  test/runtests.jl
Labels: non-breaking, performance

#2530 Update tests to Tables.jl v1.2
  NEWS.md
  Project.toml
  test/select.jl
  test/tables.jl
Labels: bug, ecosystem

#2536 code layout improvements
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/iteration.jl
  src/abstractdataframe/join.jl
  src/abstractdataframe/reshape.jl
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/index.jl
  src/subdataframe/subdataframe.jl
Labels: non-breaking

#2522 update manual and docstrings to PrettyTables.jl
  Project.toml
  docs/src/lib/internals.md
  docs/src/man/getting_started.md
  docs/src/man/joins.md
  docs/src/man/missing.md
  docs/src/man/querying_frameworks.md
  docs/src/man/reshaping_and_pivoting.md
  docs/src/man/sorting.md
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/iteration.jl
  src/abstractdataframe/join.jl
  src/abstractdataframe/reshape.jl
  src/abstractdataframe/selection.jl
  src/abstractdataframe/show.jl
  src/abstractdataframe/sort.jl
  src/dataframe/dataframe.jl
  src/dataframe/sort.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/groupeddataframe.jl
  src/subdataframe/subdataframe.jl
  test/grouping.jl
Labels: doc

#2548 Zero after decimal
  CONTRIBUTING.md
  docs/src/man/querying_frameworks.md
  test/reshape.jl
  test/show.jl
  test/tabletraits.jl
Labels: non-breaking

#2547 Optional args style
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/reshape.jl
  src/abstractdataframe/show.jl
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
Labels: non-breaking

#2546 Spaces after commas
  docs/src/lib/indexing.md
  docs/src/man/comparisons.md
  docs/src/man/getting_started.md
  docs/src/man/missing.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/io.jl
  src/abstractdataframe/iteration.jl
  src/abstractdataframe/join.jl
  src/abstractdataframe/reshape.jl
  src/abstractdataframe/selection.jl
  src/abstractdataframe/sort.jl
  src/dataframe/dataframe.jl
  src/dataframe/sort.jl
  src/dataframerow/dataframerow.jl
  src/dataframerow/utils.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/index.jl
  src/other/tables.jl
  src/subdataframe/subdataframe.jl
  test/broadcasting.jl
  test/cat.jl
  test/constructors.jl
  test/conversions.jl
  test/data.jl
  test/dataframe.jl
  test/dataframerow.jl
  test/deprecated.jl
  test/grouping.jl
  test/index.jl
  test/indexing.jl
  test/indexing_begin_tests.jl
  test/iteration.jl
  test/join.jl
  test/reshape.jl
  test/select.jl
  test/show.jl
  test/sort.jl
  test/string.jl
  test/subdataframe.jl
  test/tables.jl
  test/tabletraits.jl
Labels: non-breaking

#2551 issue #2550 fix two small typos in docs
  docs/src/lib/types.md
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/selection.jl
Labels: doc

#2552 Switch from travis to GitHub Actions for CI testing
  .github/workflows/TagBot.yml
  .github/workflows/ci.yml
  .travis.yml
  README.md
Labels: CI

#2553 error when using one dimension for indexing
  Project.toml
  src/abstractdataframe/abstractdataframe.jl
  test/indexing.jl
Labels: non-breaking

#2557 add links to curated DataFrames.jl materials
  docs/src/index.md
Labels: doc

#2559 Improve inference in `vcat`
  src/abstractdataframe/abstractdataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/index.jl
Labels: bug, non-breaking, performance

#2560 additional tests to improve coverage
  test/broadcasting.jl
  test/cat.jl
  test/constructors.jl
  test/data.jl
  test/dataframe.jl
  test/dataframerow.jl
  test/grouping.jl
  test/indexing.jl
  test/join.jl
  test/reshape.jl
  test/select.jl
  test/subdataframe.jl
Labels: CI, non-breaking

#2561 Update DataFramesMeta blurb
  docs/src/man/querying_frameworks.md
Labels: doc
