Repository JuliaData/DataFrames.jl, pull requests merged in 2020-04, with the labels that each got.

#2155 add transform and transform! and select cleanup
  docs/src/lib/functions.md
  docs/src/man/getting_started.md
  src/DataFrames.jl
  src/abstractdataframe/selection.jl
  src/other/index.jl
  test/index.jl
  test/indexing.jl
  test/select.jl
Labels: non-breaking

#2158 [BREAKING] sync combine with select
  docs/src/man/reshaping_and_pivoting.md
  docs/src/man/split_apply_combine.md
  src/deprecated.jl
  src/groupeddataframe/splitapplycombine.jl
  test/deprecated.jl
  test/grouping.jl
Labels: breaking, grouping

#2154 Fix typo
  docs/src/man/getting_started.md
Labels: doc, non-breaking

#2167 [BREAKING] add groupcols and valuecols functions
  docs/src/lib/functions.md
  src/DataFrames.jl
  src/deprecated.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/show.jl
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
Labels: breaking

#2165 [BREAKING] allow pseudo-broadcasting in select
  src/abstractdataframe/selection.jl
  src/dataframe/dataframe.jl
  test/constructors.jl
  test/select.jl
Labels: breaking

#2170 [BREAKING] add to combine and by: column selection, pseudo broadcasting, fix bug with unequal column lengths
  docs/src/man/split_apply_combine.md
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
Labels: breaking, grouping

#2176 fix deprecation in append
  src/dataframe/dataframe.jl
Labels: non-breaking

#2181 [BREAKING] Deprecate passing tuple of columns to sort
  docs/src/man/sorting.md
  src/abstractdataframe/sort.jl
  src/dataframe/sort.jl
  test/deprecated.jl
  test/sort.jl
Labels: breaking

#2177 add cols to names
  src/abstractdataframe/abstractdataframe.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/groupeddataframe.jl
  test/data.jl
Labels: non-breaking

#2183 add AsTable wrapper, disallow NamedTuple in ByRow
  docs/src/lib/types.md
  docs/src/man/getting_started.md
  docs/src/man/split_apply_combine.md
  src/DataFrames.jl
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/selection.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/utils.jl
  test/data.jl
  test/grouping.jl
  test/select.jl
Labels: grouping, non-breaking

#2189 [BREAKING] Rename deleterows! to delete!
  docs/src/lib/functions.md
  src/DataFrames.jl
  src/abstractdataframe/abstractdataframe.jl
  src/dataframe/dataframe.jl
  src/deprecated.jl
  src/subdataframe/subdataframe.jl
  test/dataframe.jl
  test/deprecated.jl
  test/subdataframe.jl
Labels: breaking

#2190 clean-up reshaping code
  src/abstractdataframe/reshape.jl
Labels: non-breaking

#2152 allow :union as cols kwarg in push! and append!
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
  src/other/tables.jl
  test/dataframe.jl
  test/tables.jl
Labels: non-breaking

#2174 [BREAKING] Deprecate aggregate
  docs/src/lib/functions.md
  docs/src/man/getting_started.md
  docs/src/man/split_apply_combine.md
  src/DataFrames.jl
  src/deprecated.jl
  src/groupeddataframe/splitapplycombine.jl
  test/data.jl
  test/deprecated.jl
  test/grouping.jl
Labels: breaking, grouping

#2188 Port to CategoricalArrays 0.8
  Project.toml
  docs/src/man/categorical.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/reshape.jl
  src/abstractdataframe/show.jl
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
  src/dataframerow/utils.jl
  src/deprecated.jl
  test/broadcasting.jl
  test/dataframe.jl
  test/grouping.jl
  test/reshape.jl
  test/tables.jl
Labels: breaking

#2201 Fix some typos
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/abstractdataframe.jl
  src/groupeddataframe/splitapplycombine.jl
Labels: non-breaking

#2199 [BREAKING] Add column indexing using strings
  Project.toml
  docs/src/lib/indexing.md
  docs/src/lib/types.md
  docs/src/man/getting_started.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/io.jl
  src/abstractdataframe/iteration.jl
  src/abstractdataframe/join.jl
  src/abstractdataframe/reshape.jl
  src/abstractdataframe/selection.jl
  src/abstractdataframe/show.jl
  src/abstractdataframe/sort.jl
  src/dataframe/dataframe.jl
  src/dataframe/sort.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/show.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/broadcasting.jl
  src/other/index.jl
  src/other/tables.jl
  src/other/utils.jl
  src/subdataframe/subdataframe.jl
  test/broadcasting.jl
  test/cat.jl
  test/constructors.jl
  test/conversions.jl
  test/data.jl
  test/dataframe.jl
  test/dataframerow.jl
  test/deprecated.jl
  test/grouping.jl
  test/index.jl
  test/indexing.jl
  test/iteration.jl
  test/reshape.jl
  test/runtests.jl
  test/select.jl
  test/sort.jl
  test/string.jl
  test/subdataframe.jl
  test/tables.jl
Labels: breaking

#2191 add Not to delete!
  src/dataframe/dataframe.jl
  test/dataframe.jl
Labels: non-breaking

#2200 [BREAKING] Circular ref bug show
  src/abstractdataframe/io.jl
  src/abstractdataframe/show.jl
  test/io.jl
Labels: breaking, bug

#2195 add mapcols! and repeat!, fix corner cases of repeat
  docs/src/lib/functions.md
  src/DataFrames.jl
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/iteration.jl
  src/dataframe/dataframe.jl
  test/iteration.jl
  test/utils.jl
Labels: feature, non-breaking

#2212 Make ByRow subtype Function
  src/abstractdataframe/selection.jl
  src/groupeddataframe/splitapplycombine.jl
Labels: non-breaking
