Repository JuliaData/DataFrames.jl, pull requests merged in 2020-06, with the labels that each got.

#2273 fix bugs in append! and push! corner cases
  Project.toml
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
  test/dataframe.jl
Labels: backport, bug, priority

#2274 [BREAKING] Keep naming ComposedFunction :function
  src/other/utils.jl
  test/grouping.jl
  test/select.jl
  test/utils.jl
Labels: breaking

#2284 let indicator allow strings
  src/abstractdataframe/join.jl
  test/join.jl
Labels: backport, non-breaking

#2163 Add .editorconfig and comment on GitHub Actions
  .editorconfig
  CONTRIBUTING.md
Labels: doc, non-breaking

#2288 add eltypes to show docstring
  src/abstractdataframe/show.jl
Labels: backport, doc, non-breaking

#2282 improve error message when validating
  src/abstractdataframe/join.jl
  test/join.jl
Labels: backport, non-breaking

#2299 fixes to follow breaking changes in printing in 1.6
  src/abstractdataframe/io.jl
  src/abstractdataframe/show.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/show.jl
Labels: backport, non-breaking

#2280 Fix various bugs in split/apply/combine in 0.21 release
  src/abstractdataframe/selection.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
  test/select.jl
Labels: backport, bug, grouping, non-breaking, priority

#2296 improve handling of indicator in joins
  src/abstractdataframe/join.jl
  test/join.jl
Labels: backport, bug, non-breaking

#2290 add handling to cases when all is not optimized out
  Project.toml
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
Labels: backport, non-breaking, performance

#2292 [BREAKING] stricter isless for DataFrameRow
  src/dataframerow/dataframerow.jl
  test/dataframerow.jl
Labels: breaking

#2279 add filter and filter! to GroupedDataFrame
  src/abstractdataframe/abstractdataframe.jl
  src/groupeddataframe/groupeddataframe.jl
  test/grouping.jl
Labels: feature, grouping, non-breaking

#2303 move lock inside if clause
  src/groupeddataframe/groupeddataframe.jl
Labels: backport, performance

#2291 [BREAKING] Make DataFrameColumns stop being an AbstractVector
  docs/src/lib/functions.md
  docs/src/lib/types.md
  src/abstractdataframe/iteration.jl
  src/dataframe/dataframe.jl
  src/deprecated.jl
  src/subdataframe/subdataframe.jl
  test/dataframe.jl
  test/indexing_begin_tests.jl
  test/iteration.jl
  test/reshape.jl
  test/select.jl
  test/tables.jl
Labels: breaking, feature

#2307 update DataFrameRow documentation
  src/dataframerow/dataframerow.jl
Labels: backport, doc

#2311 fix show of UnionAll
  Project.toml
  src/abstractdataframe/show.jl
  test/show.jl
Labels: backport, bug, non-breaking, priority
