Repository JuliaData/DataFrames.jl, pull requests merged in 2020-07, with the labels that each got.

#2315 Up Documenter.jl
  docs/Project.toml
Labels: backport, doc, non-breaking

#2320 fix deprecated example in the docs for innerjoin
  docs/src/man/joins.md
Labels: backport, doc

#2333 fix DataFrameRow setindex!
  Project.toml
  src/dataframe/dataframe.jl
  test/indexing.jl
Labels: backport, bug, priority

#2335 Don't specialize groupreduce! on result array element type
  src/groupeddataframe/splitapplycombine.jl
Labels: backport, bug, priority

#2338 Deprecate dataframe bang
  docs/src/lib/types.md
  docs/src/man/getting_started.md
  src/DataFrames.jl
  src/dataframe/dataframe.jl
  src/deprecated.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/tables.jl
  test/constructors.jl
  test/dataframe.jl
  test/deprecated.jl
  test/grouping.jl
  test/tables.jl
Labels: breaking, decision
