Repository JuliaData/DataFrames.jl, pull requests merged in 2020-10, with the labels that each got.

#2463 Improve docstring of DataFrame
  src/dataframe/dataframe.jl
Labels: doc

#2462 improve references to indexing rules in the manual
  docs/src/man/getting_started.md
Labels: doc

#2392 add in for GroupKeys
  NEWS.md
  src/groupeddataframe/groupeddataframe.jl
  test/grouping.jl
Labels: grouping, non-breaking

#2468 New recommendations in contributing guidelines
  CONTRIBUTING.md
Labels: doc

#2466 fix setproperty! for data frame
  src/dataframe/dataframe.jl
  src/subdataframe/subdataframe.jl
  test/indexing.jl
Labels: bug, non-breaking

#2461 Allow multicolumn transformations for AbstractDataFrame
  NEWS.md
  docs/src/lib/types.md
  docs/src/man/getting_started.md
  src/abstractdataframe/selection.jl
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
  test/select.jl
Labels: breaking, priority

#2442 [BREAKING] Use DataAPI.refpool for optimized grouping
  Project.toml
  src/dataframerow/utils.jl
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
Labels: breaking, ecosystem, performance

#2476 allow passing empty sets of columns to ByRow and filter
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/selection.jl
  src/groupeddataframe/splitapplycombine.jl
  test/data.jl
  test/grouping.jl
Labels: feature, grouping, non-breaking

#2427 remove dependency on CategoricalArrays.jl in legacy show
  src/abstractdataframe/show.jl
  test/show.jl
Labels: ecosystem, non-breaking

#2447 Implement permutedims
  NEWS.md
  docs/src/lib/functions.md
  docs/src/man/reshaping_and_pivoting.md
  src/abstractdataframe/reshape.jl
  test/reshape.jl
Labels: feature, hacktoberfest-accepted, non-breaking

#2495 add Cols support
  NEWS.md
  Project.toml
  docs/src/lib/indexing.md
  docs/src/man/getting_started.md
  docs/src/man/sorting.md
  docs/src/man/split_apply_combine.md
  src/DataFrames.jl
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/selection.jl
  src/dataframerow/dataframerow.jl
  src/other/index.jl
  test/data.jl
  test/dataframe.jl
  test/deprecated.jl
  test/grouping.jl
  test/index.jl
  test/iteration.jl
  test/reshape.jl
  test/select.jl
  test/sort.jl
  test/string.jl
Labels: feature, non-breaking

#2501 make sure by isa Function or a vector of functions
  src/abstractdataframe/sort.jl
Labels: bug

#2503 Remove type parameters in DataFrameJoiner
  src/abstractdataframe/join.jl
  src/dataframerow/utils.jl
  test/join.jl
Labels: bug

#2494 [BREAKING] Refactor unstack
  NEWS.md
  docs/src/man/reshaping_and_pivoting.md
  src/abstractdataframe/reshape.jl
  test/reshape.jl
Labels: breaking, ecosystem
