Repository JuliaData/DataFrames.jl, pull requests merged in 2021-04, with the labels that each got.

#2701 Fix typo in unstack docstring
  src/abstractdataframe/reshape.jl
Labels: doc

#2700 promoted documentation on working with DataFrames
  docs/make.jl
  docs/src/man/getting_started.md
  docs/src/man/importing_and_exporting.md
  docs/src/man/working_with_dataframes.md
Labels: doc

#2690 check for data frame corruption in delete!
  NEWS.md
  src/dataframe/dataframe.jl
  test/dataframe.jl
Labels: non-breaking

#2691 Inference improvements
  src/abstractdataframe/selection.jl
  src/abstractdataframe/subset.jl
  src/groupeddataframe/complextransforms.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/precompile.jl
Labels: performance, priority

#2703 Enable doctests
  docs/Project.toml
  docs/make.jl
  docs/src/man/categorical.md
  docs/src/man/getting_started.md
  docs/src/man/joins.md
  docs/src/man/missing.md
  docs/src/man/querying_frameworks.md
  docs/src/man/reshaping_and_pivoting.md
  docs/src/man/sorting.md
  docs/src/man/split_apply_combine.md
  docs/src/man/working_with_dataframes.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/io.jl
  src/abstractdataframe/iteration.jl
  src/abstractdataframe/reshape.jl
  src/abstractdataframe/selection.jl
  src/abstractdataframe/show.jl
  src/abstractdataframe/sort.jl
  src/abstractdataframe/subset.jl
  src/dataframe/dataframe.jl
  src/dataframe/sort.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/groupeddataframe.jl
  src/join/composer.jl
  src/subdataframe/subdataframe.jl
Labels: doc

#2708 Fix grouping aggregation slowdown
  src/groupeddataframe/fastaggregates.jl
  test/grouping.jl
Labels: grouping, performance

#2694 do not use collect in describe
  src/abstractdataframe/abstractdataframe.jl
Labels: performance

#2685 Enable multithreading in hashrows_col!
  benchmarks/grouping_performance.jl
  docs/src/lib/internals.md
  src/groupeddataframe/utils.jl
  src/other/utils.jl
Labels: grouping, performance

#2710 Fix default copycols for Tables.jl constructor
  src/other/tables.jl
  test/tables.jl
Labels: ecosystem

#2687 Use fast path for single column aggs
  src/abstractdataframe/selection.jl
  test/select.jl
Labels: grouping

#2716 Replace `tforeach` with `@spawn_for_chunks`
  docs/src/lib/internals.md
  src/groupeddataframe/utils.jl
  src/other/utils.jl
Labels: grouping, performance

#2707 Improve structure of join benchmarks
  benchmarks/join_performance.jl
  benchmarks/joins/join_performance.jl
  benchmarks/joins/runtests.jl
  benchmarks/run.sh
Labels: CI, performance

#2709 Despecialization part 2
  src/groupeddataframe/callprocessing.jl
  src/groupeddataframe/complextransforms.jl
  src/groupeddataframe/fastaggregates.jl
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
Labels: grouping, performance

#2718 update precompilation statements
  src/other/precompile.jl
Labels: performance

#2719 additional precompilation for all=true
  src/other/precompile.jl
Labels: performance

#2720 Bk/clean exports
  src/DataFrames.jl
  src/deprecated.jl
  src/other/precompile.jl
Labels: non-breaking

#2721 make renaming perform copy in transform and transform!
  NEWS.md
  src/abstractdataframe/selection.jl
  src/other/precompile.jl
  test/select.jl
Labels: bug

#2729 Prepare for 1.0 release
  NEWS.md
  Project.toml
Labels: ecosystem

#2733 fix PooledArray performance bottleneck
  Project.toml
  src/groupeddataframe/utils.jl
Labels: grouping, performance
