Repository JuliaData/DataFrames.jl, pull requests merged in 2021-01, with the labels that each got.

#2592 Avoid performance bottleneck corner case in grouping
  src/dataframerow/utils.jl
Labels: grouping, non-breaking, performance

#2496 Add subset
  NEWS.md
  docs/src/lib/functions.md
  docs/src/man/comparisons.md
  src/DataFrames.jl
  src/abstractdataframe/subset.jl
  test/grouping.jl
Labels: grouping, non-breaking, priority

#2574 Enable multithreading with several operations in combine/select/transform
  .github/workflows/ci.yml
  Project.toml
  docs/src/man/split_apply_combine.md
  src/DataFrames.jl
  src/abstractdataframe/selection.jl
  src/groupeddataframe/fastaggregates.jl
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
  test/runtests.jl
  test/utils.jl
Labels: grouping, performance

#2601 Fix groupreduce with var and std for Unitful types
  Project.toml
  src/groupeddataframe/fastaggregates.jl
  test/grouping.jl
Labels: backport, bug, grouping

#2608 Use PrettyTables.jl's alignment anchor for numbers
  Project.toml
  src/abstractdataframe/prettytables.jl
  src/abstractdataframe/show.jl
Labels: display

#2594 add firstindex check and fix a bug in mapcols!
  NEWS.md
  Project.toml
  docs/src/lib/types.md
  src/abstractdataframe/iteration.jl
  src/abstractdataframe/selection.jl
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
  test/indexing.jl
  test/indexing_offset.jl
  test/iteration.jl
  test/select.jl
Labels: bug, decision

#2614 Support new PooledArrays 1.0 release
  Project.toml
Labels: ecosystem, non-breaking

#2615 Fix missing mention of transform in manual
  docs/src/man/getting_started.md
Labels: doc

#2417 add predicate support for names and more tests
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/groupeddataframe.jl
  test/dataframe.jl
Labels: feature, non-breaking
