Repository JuliaData/DataFrames.jl, pull requests merged in 2021-11, with the labels that each got.

#2918 Add broadcasting of selectors to the minilanguage
  NEWS.md
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/selection.jl
  src/groupeddataframe/splitapplycombine.jl
  test/select.jl
Labels: bug, feature

#2922 Fix tests of names
  test/dataframe.jl
Labels: ecosystem

#2459 Add standard deviation and 25% and 75% quantiles to `describe` :detailed
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  test/dataframe.jl
Labels: breaking

#2926 Allow passing multiple columns to subset
  NEWS.md
  docs/src/man/working_with_dataframes.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/subset.jl
  src/groupeddataframe/groupeddataframe.jl
  test/subset.jl
Labels: feature

#2934 Correctly handle functors when auto-generating column names
  src/other/utils.jl
  test/select.jl
Labels: bug

#2923 Update ci.yml in preparation of Julia 1.6 LTS
  .github/workflows/ci.yml
Labels: CI

#2937 plan for a change in broadcasting rules in Julia 1.7
  NEWS.md
  src/other/broadcasting.jl
Labels: feature

#2854 deprecate delete!, define deleteat!
  NEWS.md
  docs/src/lib/functions.md
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/subset.jl
  src/dataframe/dataframe.jl
  src/deprecated.jl
  src/groupeddataframe/groupeddataframe.jl
  src/other/precompile.jl
  src/subdataframe/subdataframe.jl
  test/data.jl
  test/dataframe.jl
  test/deprecated.jl
  test/subdataframe.jl
Labels: feature

#2904 Try to detect unicode normalization issues in column names
  src/other/index.jl
  test/indexing.jl
Labels: feature

#2938 Change join tests to reduce memory consumption
  test/join.jl
Labels: CI

#2943 Reduce test memory usage
  test/indexing.jl
Labels: CI

#2941 Add examples for `issorted` docstrings.
  NEWS.md
  src/abstractdataframe/sort.jl
  src/dataframe/sort.jl
Labels: feature, doc

#2942 Add row indexing to filter docstring and examples.
  docs/src/lib/indexing.md
  src/abstractdataframe/abstractdataframe.jl
Labels: doc

#2949 Catch OutOfMemoryError
  test/join.jl
Labels: CI

#2948 Make transformation docstring more precise
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/selection.jl
Labels: doc

#2944 Add `reverse` prototype
  NEWS.md
  docs/src/lib/functions.md
  src/abstractdataframe/abstractdataframe.jl
  test/dataframe.jl
Labels: feature

#2946 Define sort! for AbstractDataFrame and fix issues of kwargs in sorting functions
  NEWS.md
  docs/src/man/sorting.md
  src/DataFrames.jl
  src/abstractdataframe/sort.jl
  src/dataframe/sort.jl
  test/sort.jl
Labels: bug, feature

#2950 clean up source code
  docs/src/man/comparisons.md
  docs/src/man/getting_started.md
  docs/src/man/importing_and_exporting.md
  docs/src/man/joins.md
  docs/src/man/missing.md
  docs/src/man/split_apply_combine.md
  docs/src/man/working_with_dataframes.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/io.jl
  src/abstractdataframe/reshape.jl
  src/abstractdataframe/selection.jl
  src/abstractdataframe/show.jl
  src/abstractdataframe/sort.jl
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/groupeddataframe.jl
  src/join/composer.jl
  src/join/inplace.jl
  src/subdataframe/subdataframe.jl
  test/broadcasting.jl
  test/cat.jl
  test/constructors.jl
  test/data.jl
  test/dataframe.jl
  test/dataframerow.jl
  test/deprecated.jl
  test/duplicates.jl
  test/grouping.jl
  test/indexing.jl
  test/io.jl
  test/iteration.jl
  test/join.jl
  test/reshape.jl
  test/select.jl
  test/show.jl
  test/sort.jl
  test/string.jl
  test/subdataframe.jl
  test/subset.jl
  test/tables.jl
  test/utils.jl
Labels: CI
