Repository JuliaData/DataFrames.jl, pull requests merged in 2021-06, with the labels that each got.

#2773 add information how DelimitedFiles can be used
  docs/src/index.md
  docs/src/man/importing_and_exporting.md
Labels: doc

#2724 Matchmissing == :notequal
  NEWS.md
  src/join/composer.jl
  test/join.jl
Labels: feature, joins

#2778 remove escape in Char
  test/show.jl
Labels: CI

#2780 allow :col => AsTable and :col => cols
  NEWS.md
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/selection.jl
  test/select.jl
Labels: bug, feature

#2786 Use latest Documenter.jl
  docs/Project.toml
Labels: CI

#2782 allow Matrices in transformations of GroupedDataFrame
  NEWS.md
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
Labels: bug, grouping

#2777 Deprecate AbstractVector in hcat
  NEWS.md
  Project.toml
  src/abstractdataframe/abstractdataframe.jl
  src/dataframe/dataframe.jl
  test/cat.jl
  test/deprecated.jl
Labels: feature

#2801 move summary outside of a <table> in text/html
  NEWS.md
  src/abstractdataframe/io.jl
  test/dataframerow.jl
  test/grouping.jl
  test/io.jl
Labels: bug, display

#2807 up DataAPI.jl to 1.7 and CategoricalArrays.jl to 0.10.0
  Project.toml
  src/DataFrames.jl
  src/join/composer.jl
  test/join.jl
Labels: CI, ecosystem

#2791 Fix float grouping
  NEWS.md
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/utils.jl
  test/grouping.jl
Labels: bug

#2805 Add some clarifying comments on copycols for Tables.jl inputs
  docs/src/lib/types.md
  src/dataframe/dataframe.jl
Labels: doc
