Repository JuliaData/DataFrames.jl, pull requests merged in 2021-05, with the labels that each got.

#2736 fix row_group_slots_threading
  Project.toml
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/utils.jl
  src/other/precompile.jl
  src/other/utils.jl
  test/grouping.jl
  test/utils.jl
Labels: grouping, performance

#2744 require AbstractVector from subset selectors
  NEWS.md
  Project.toml
  src/abstractdataframe/subset.jl
  test/grouping.jl
  test/runtests.jl
  test/subset.jl
Labels: bug

#2726 Optimize `completecases` to process only missingable columns
  src/abstractdataframe/abstractdataframe.jl
  test/data.jl
Labels: performance

#2749 fix performance issue in multirow split-apply-combine
  NEWS.md
  Project.toml
  src/groupeddataframe/callprocessing.jl
  src/groupeddataframe/complextransforms.jl
  src/groupeddataframe/splitapplycombine.jl
Labels: grouping, performance

#2752 Update docs URLs in README
  README.md
Labels: doc

#2759 make "Edit on Github" points to main branch
  docs/make.jl
Labels: doc

#2725 Update comparisons with data.table info
  docs/src/man/comparisons.md
Labels: doc

#2758 audit more master -> main
  README.md
  docs/src/index.md
Labels: doc

#2727 Run `findall(rows)` only if `rows` are not all true
  src/other/utils.jl
  src/subdataframe/subdataframe.jl
  test/utils.jl
Labels: performance

#2756 Alignment of complex numbers
  src/abstractdataframe/show.jl
  test/show.jl
Labels: display

#2763 update NEWS.md
  NEWS.md
Labels: doc

#2751 Cover corner case of compactype (wide name and CategoricalValue)
  test/show.jl
Labels: CI, display

#2771 Explicit loop in `_findall` to avoid allocations
  src/other/utils.jl
  test/utils.jl
Labels: performance

#2774 Put longer type into th title argument in HTML show
  NEWS.md
  src/abstractdataframe/io.jl
  test/dataframerow.jl
  test/grouping.jl
  test/io.jl
Labels: display

#2769 add _findall for AbstractVector{Bool} and use it in internal functions
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  src/dataframe/dataframe.jl
  src/join/composer.jl
  src/other/index.jl
  src/other/utils.jl
  test/index.jl
  test/utils.jl
Labels: performance

#2746 Fix type instability in sort for few columns case and fix issorted bug
  NEWS.md
  src/abstractdataframe/sort.jl
  src/other/precompile.jl
  test/sort.jl
Labels: bug, performance
