Repository JuliaData/DataFrames.jl, pull requests merged in 2021-09, with the labels that each got.

#2829 feat: `insertcols!` receives kwarg `after`
  NEWS.md
  src/dataframe/dataframe.jl
  test/dataframe.jl
Labels: feature, non-breaking

#2794 Support adding columns to views
  NEWS.md
  docs/src/lib/indexing.md
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/selection.jl
  src/dataframe/dataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/broadcasting.jl
  src/subdataframe/subdataframe.jl
  test/broadcasting.jl
  test/grouping.jl
  test/indexing.jl
  test/runtests.jl
  test/select.jl
  test/subdataframe_mutation.jl
Labels: bug, feature

#2851 Improve docstring of AsTable
  src/other/utils.jl
Labels: doc

#2856 use nrow and ncol from DataAPI.j
  Project.toml
  src/DataFrames.jl
Labels: ecosystem

#2862 fix transpose error message and clean up code
  src/abstractdataframe/reshape.jl
  src/abstractdataframe/sort.jl
  test/grouping.jl
  test/reshape.jl
Labels: CI

#2843 Bk/add leftjoin!
  NEWS.md
  docs/src/lib/functions.md
  src/DataFrames.jl
  src/join/composer.jl
  src/join/inplace.jl
  test/join.jl
Labels: feature, joins

#2837 more careful test of ByRow for PooledArray
  Project.toml
  test/select.jl
Labels: bug

#2859 make DataFrame constructor more flexible
  NEWS.md
  src/dataframe/dataframe.jl
  test/constructors.jl
Labels: feature

#2828 feat: `unstack` receives kwarg `fillvalue`
  NEWS.md
  src/abstractdataframe/reshape.jl
  test/reshape.jl
Labels: feature, non-breaking

#2865 update docs following CSV.jl 0.9 release
  docs/src/man/basics.md
  docs/src/man/querying_frameworks.md
  docs/src/man/reshaping_and_pivoting.md
  docs/src/man/sorting.md
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/io.jl
  src/abstractdataframe/show.jl
  test/io.jl
Labels: doc

#2878 Allow constructing Matrix from empty dataframe
  src/abstractdataframe/abstractdataframe.jl
  test/conversions.jl
Labels: bug

#2880 Fix typo in NEWS.md
  NEWS.md
Labels: doc

#2882 Improve docstring for names()
  docs/src/man/getting_started.md
  src/abstractdataframe/abstractdataframe.jl
Labels: doc

#2868 code cleanup to improve error messages
  src/abstractdataframe/abstractdataframe.jl
  src/other/index.jl
Labels: feature

#2889 avoid not specialized Pair issue
  NEWS.md
  src/abstractdataframe/selection.jl
  src/groupeddataframe/splitapplycombine.jl
  test/select.jl
Labels: bug
