Repository JuliaData/DataFrames.jl, pull requests merged in 2021-12, with the labels that each got.

#2951 Add `view` kwarg to `first` and `last`
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  test/dataframe.jl
Labels: feature

#2955 Generate precompile statements for Julia 1.7
  Project.toml
  src/other/precompile.jl
Labels: CI

#2967 fix issues with parameter type printing in doctests
  docs/src/man/basics.md
  src/abstractdataframe/iteration.jl
Labels: doc

#2966 better disallowmissing error message
  src/abstractdataframe/abstractdataframe.jl
  src/dataframe/dataframe.jl
  test/dataframe.jl
Labels: feature

#2970 fix getindex with vector of Pairs
  NEWS.md
  Project.toml
  src/dataframe/dataframe.jl
  src/subdataframe/subdataframe.jl
  test/indexing.jl
Labels: bug
