Repository JuliaData/DataFrames.jl, pull requests merged in 2021-03, with the labels that each got.

#2622 left, right and outerjoin rewrite
  NEWS.md
  Project.toml
  benchmarks/join_performance.jl
  benchmarks/run.sh
  benchmarks/runtests.jl
  src/DataFrames.jl
  src/join/composer.jl
  src/join/core.jl
  src/other/precompile.jl
  test/data.jl
  test/join.jl
Labels: bug, performance, priority

#2645 fix broadcasting tests for Julia 1.7
  test/broadcasting.jl
Labels: CI

#2644 fix split-apply-combine tests
  test/grouping.jl
Labels: CI

#2646 Fix CategoricalArrays.jl in Project.toml
  Project.toml
Labels: CI

#2648 fix repeat and some other minor issues
  src/abstractdataframe/abstractdataframe.jl
  src/dataframe/dataframe.jl
  test/broadcasting.jl
  test/subdataframe.jl
  test/utils.jl
Labels: CI, bug

#2656 Respect copycols when building DataFrame from Tables.CopiedColumns
  src/other/tables.jl
  test/tables.jl
Labels: ecosystem

#2652 update describe, unique and nonunique docs
  src/abstractdataframe/abstractdataframe.jl
  test/data.jl
  test/dataframe.jl
Labels: doc

#2649 add vcat with source; deprecate indicator in joins in favor of source
  NEWS.md
  docs/src/lib/functions.md
  docs/src/man/joins.md
  src/abstractdataframe/abstractdataframe.jl
  src/join/composer.jl
  test/dataframe.jl
  test/deprecated.jl
  test/join.jl
Labels: feature, non-breaking

#2647 use multithreading in basic operations
  NEWS.md
  benchmarks/constructor_and_indexing/constructor_and_indexing_performance.jl
  benchmarks/constructor_and_indexing/run.sh
  benchmarks/joins/join_performance.jl
  benchmarks/joins/run.sh
  benchmarks/joins/runtests.jl
  src/dataframe/dataframe.jl
  test/constructors.jl
  test/indexing.jl
Labels: non-breaking, performance

#2661 Use multithreading in row_group_slots refarray method
  benchmarks/grouping_performance.jl
  docs/src/lib/internals.md
  src/dataframerow/utils.jl
  src/other/utils.jl
  test/grouping.jl
  test/utils.jl
Labels: grouping, performance

#2664 Support threading in joined column creation
  NEWS.md
  src/join/composer.jl
  test/join.jl
Labels: non-breaking, performance

#2671 Deprecate unnecessary convert methods
  NEWS.md
  Project.toml
  src/abstractdataframe/abstractdataframe.jl
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
  src/deprecated.jl
  src/groupeddataframe/groupeddataframe.jl
  test/conversions.jl
  test/deprecated.jl
  test/grouping.jl
Labels: non-breaking

#2655 add support for getproperty broadcasting
  NEWS.md
  docs/src/lib/indexing.md
  src/other/broadcasting.jl
  test/broadcasting.jl
  test/deprecated.jl
Labels: breaking, decision

#2669 add ==, isequal <, and isless for DataFrameRow and GroupKey
  NEWS.md
  src/DataFrames.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/utils.jl
  src/other/precompile.jl
  src/other/utils.jl
  test/dataframerow.jl
  test/grouping.jl
Labels: breaking, bug, feature, grouping

#2680 make Tables.columns(df) return eachcol(df)
  src/other/tables.jl
Labels: ecosystem

#2686 Reduce test memory consumption
  test/indexing.jl
Labels: CI

#2682 check if column order is correct in aggregations
  src/DataFrames.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/complextransforms.jl
  src/groupeddataframe/groupeddataframe.jl
  src/other/names.jl
  test/grouping.jl
Labels: bug, grouping
