Repository JuliaData/DataFrames.jl, pull requests merged in 2022-04, with the labels that each got.

#3035 Use cycle notation to speed up `permute!`
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  test/dataframe.jl
Labels: performance

#3037 Make indexing of eachrow return the object of the same type on a view of the parent
  NEWS.md
  src/abstractdataframe/iteration.jl
  test/iteration.jl
Labels: performance

#3040 make sure we correctly pass matchmissing in joins
  src/join/composer.jl
  test/join.jl
Labels: bug

#3032 allow scalars in subset and subset! as conditions
  NEWS.md
  src/abstractdataframe/subset.jl
  test/subset.jl
Labels: decision
