Repository JuliaData/DataFrames.jl, pull requests merged in 2022-10, with the labels that each got.

#3187 improve printing of GroupedDataFrame in corner cases
  src/groupeddataframe/show.jl
  test/show.jl
Labels: display

#3185 rename valuestransform to combine in unstack
  NEWS.md
  docs/src/man/reshaping_and_pivoting.md
  src/abstractdataframe/reshape.jl
  test/deprecated.jl
  test/metadata.jl
  test/multithreading.jl
  test/reshape.jl
Labels: decision

#3189 Sync metadata implementation with DataAPI.jl 1.12.0
  Project.toml
  src/other/metadata.jl
  test/metadata.jl
Labels: ecosystem

#3190 Fix deprecation warning when sorting data frame with no columns
  src/abstractdataframe/sort.jl
  src/other/metadata.jl
  test/sort.jl
Labels: bug

#3192 make sure getindex on DataFrameRows does not alias passed selector
  NEWS.md
  Project.toml
  src/abstractdataframe/iteration.jl
  test/iteration.jl
Labels: bug

#3198 make sure flatten works corretly on a data frame with zero rows
  NEWS.md
  Project.toml
  src/abstractdataframe/abstractdataframe.jl
  test/reshape.jl
Labels: bug

#3195 Mention DataFrameMacros.jl in the docs
  docs/Project.toml
  docs/src/index.md
  docs/src/man/querying_frameworks.md
  docs/src/man/working_with_dataframes.md
Labels: doc

#3201 improve manual entry of assignment to a data frame
  docs/src/man/basics.md
  docs/src/man/getting_started.md
Labels: doc
