Repository JuliaData/DataFrames.jl, pull requests merged in 2022-09, with the labels that each got.

#3137 Remove unused where clauses
  src/abstractdataframe/sort.jl
  src/dataframe/dataframe.jl
Labels: ecosystem

#3158 Synchronize ByRow and Tables.subset with Tables.jl 1.8
  NEWS.md
  Project.toml
  docs/src/lib/types.md
  src/DataFrames.jl
  src/abstractdataframe/selection.jl
  src/other/tables.jl
  test/grouping.jl
  test/tables.jl
Labels: ecosystem

#3156 Fix broken links in docs
  docs/src/index.md
  docs/src/man/getting_started.md
Labels: doc

#3157 further improve OutOfMemory problem handling in tests
  test/join.jl
Labels: CI

#3146 add :nnonunique and :nuniqueall to describe
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  test/dataframe.jl
Labels: feature

#3155 Fix type assertion in _filter_helper
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
Labels: bug

#3160 Fix docstring of semijoin and antijoin
  src/join/composer.jl
Labels: doc

#3164 synch NEWS.md between 1.4 and 1.3 branches
  NEWS.md
Labels: doc

#3055 Metadata on data frame and column level
  NEWS.md
  Project.toml
  docs/make.jl
  docs/src/lib/functions.md
  docs/src/lib/metadata.md
  src/DataFrames.jl
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/iteration.jl
  src/abstractdataframe/reshape.jl
  src/abstractdataframe/selection.jl
  src/abstractdataframe/sort.jl
  src/abstractdataframe/subset.jl
  src/dataframe/dataframe.jl
  src/dataframe/insertion.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/splitapplycombine.jl
  src/join/composer.jl
  src/join/inplace.jl
  src/other/broadcasting.jl
  src/other/index.jl
  src/other/metadata.jl
  src/other/tables.jl
  src/subdataframe/subdataframe.jl
  test/data.jl
  test/metadata.jl
  test/runtests.jl
Labels: feature, metadata

#3145 Require Julia 1.6
  .github/workflows/ci.yml
  NEWS.md
  Project.toml
  src/DataFrames.jl
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/iteration.jl
  src/abstractdataframe/show.jl
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
  src/groupeddataframe/complextransforms.jl
  src/groupeddataframe/fastaggregates.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  src/join/composer.jl
  src/other/broadcasting.jl
  src/other/precompile.jl
  src/other/utils.jl
  test/broadcasting.jl
  test/dataframe.jl
  test/grouping.jl
  test/indexing.jl
  test/io.jl
  test/multithreading.jl
  test/runtests.jl
  test/select.jl
  test/show.jl
  test/subdataframe_mutation.jl
Labels: ecosystem

#3166 improve error message when column is not found
  src/other/index.jl
Labels: display

#3172 Reduce memory use in threading correctness tests
  test/indexing.jl
Labels: CI

#3165 add ShiftedArrays 2.x support
  Project.toml
  test/select.jl
  test/subdataframe_mutation.jl
Labels: ecosystem

#3169 Improve metadata documentation
  docs/src/lib/metadata.md
Labels: doc

#3096 Use PrettyTables.jl as HTML backend
  Project.toml
  docs/src/man/getting_started.md
  src/abstractdataframe/io.jl
  src/abstractdataframe/prettytables.jl
  src/abstractdataframe/show.jl
  src/dataframerow/show.jl
  src/groupeddataframe/show.jl
  test/dataframerow.jl
  test/grouping.jl
  test/io.jl
  test/show.jl
Labels: display

#3115 1-arg permutedims(df)
  src/abstractdataframe/reshape.jl
  test/reshape.jl
Labels: decision

#3177 Add better error message on error when pushing rows to a data frame
  src/dataframe/insertion.jl
Labels: feature

#3178 improve names docstring
  src/abstractdataframe/abstractdataframe.jl
Labels: doc

#3181 switch from view to viewhint in Tables.subset
  Project.toml
  src/other/tables.jl
  test/tables.jl
Labels: ecosystem

#3179 Avoid method dispatch ambiguities in DataFrames.jl
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/sort.jl
  src/groupeddataframe/fastaggregates.jl
  src/groupeddataframe/groupeddataframe.jl
  src/other/broadcasting.jl
  src/subdataframe/subdataframe.jl
  test/broadcasting.jl
  test/dataframe.jl
  test/grouping.jl
  test/runtests.jl
  test/sort.jl
  test/subdataframe.jl
Labels: bug

#3183 enable multithreading tests of joins only on 64 bit machines
  test/join.jl
Labels: CI

#3107 Improved REPL printing for GroupedDataFrames
  docs/src/man/split_apply_combine.md
  src/groupeddataframe/show.jl
  test/show.jl
Labels: display
