Repository JuliaData/DataFrames.jl, pull requests merged in 2022-06, with the labels that each got.

#3064 make AsTable more careful when accepting argument
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/selection.jl
  src/other/utils.jl
  test/index.jl
Labels: bug, decision

#3067 add extra safety step in filter with AsTable
  src/groupeddataframe/groupeddataframe.jl
Labels: grouping

#3047 add resize!, keepat!, pop!, popfist!, popat!
  NEWS.md
  Project.toml
  docs/src/lib/functions.md
  src/DataFrames.jl
  src/dataframe/dataframe.jl
  test/dataframe.jl
Labels: feature

#3068 add prepend!
  docs/src/lib/functions.md
  src/dataframe/dataframe.jl
  src/other/tables.jl
  test/dataframe.jl
Labels: feature

#3030 Add a keyword argument to disable multithreading
  NEWS.md
  docs/src/lib/functions.md
  docs/src/lib/internals.md
  src/abstractdataframe/reshape.jl
  src/abstractdataframe/selection.jl
  src/abstractdataframe/subset.jl
  src/groupeddataframe/complextransforms.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/utils.jl
  test/multithreading.jl
  test/runtests.jl
  test/utils.jl
Labels: performance, multithreading

#3071 patch deleteat!
  src/dataframe/dataframe.jl
  test/dataframe.jl
Labels: bug

#3070 Performance of transform! on SubDataFrame
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/selection.jl
  src/dataframe/dataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  src/subdataframe/subdataframe.jl
  test/select.jl
Labels: bug, performance, grouping

#3081 Fix vcat in case no data frames are passed
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  test/dataframe.jl
Labels: bug

#3072 Add insert! and pushfirst!
  NEWS.md
  docs/src/lib/functions.md
  docs/src/man/getting_started.md
  src/DataFrames.jl
  src/dataframe/dataframe.jl
  src/dataframe/insertion.jl
  src/dataframerow/dataframerow.jl
  test/dataframe.jl
  test/insertion.jl
  test/runtests.jl
Labels: feature

#3083 Improve documentation and speedup isempty
  docs/src/lib/functions.md
  src/abstractdataframe/abstractdataframe.jl
  src/dataframe/dataframe.jl
  src/subdataframe/subdataframe.jl
  test/dataframe.jl
Labels: doc

#3089 Improve join error message
  src/join/composer.jl
  test/join.jl
Labels: joins

#3087 Add more examples of operation specification language
  docs/src/man/working_with_dataframes.md
Labels: doc

#3092 fix wrong docs of outerjoin
  src/join/composer.jl
Labels: doc
