Repository JuliaData/DataFrames.jl, pull requests merged in 2022-02, with the labels that each got.

#2999 Use `julia-actions/cache`; also for the `docs` job
  .github/workflows/ci.yml
Labels: CI

#3002 Handle Base.CanonicalIndexError introduced in Julia 1.8
  test/indexing_offset.jl
Labels: CI

#2998 allow function in allowduplicates in unstack
  NEWS.md
  Project.toml
  docs/src/man/reshaping_and_pivoting.md
  src/abstractdataframe/reshape.jl
  test/reshape.jl
Labels: feature, reshaping

#3001 Implementation of eachindex, proprow, and groupindices
  NEWS.md
  docs/src/lib/functions.md
  docs/src/man/split_apply_combine.md
  src/DataFrames.jl
  src/abstractdataframe/selection.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/splitapplycombine.jl
  test/grouping.jl
Labels: feature, grouping

#3006 add `first`, `last` methods with `n` for gdf
  NEWS.md
  src/groupeddataframe/groupeddataframe.jl
  test/grouping.jl
Labels: feature

#3010 add reverse!, shuffle, shuffle!, permute!, and invpermute!
  NEWS.md
  Project.toml
  docs/src/lib/functions.md
  src/DataFrames.jl
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/sort.jl
  test/dataframe.jl
Labels: feature

#3009 Improved error when column numbers do not match in transformations
  src/abstractdataframe/selection.jl
  src/groupeddataframe/splitapplycombine.jl
  test/select.jl
Labels: feature
