Repository JuliaData/DataFrames.jl, pull requests merged in 2023-07, with the labels that each got.

#3348 Correctly handle Tables.AbstractRow in operation specficiation
  NEWS.md
  docs/src/man/split_apply_combine.md
  src/abstractdataframe/selection.jl
  src/groupeddataframe/callprocessing.jl
  src/groupeddataframe/complextransforms.jl
  src/groupeddataframe/splitapplycombine.jl
  src/other/names.jl
  test/grouping.jl
  test/select.jl
Labels: feature

#3353 fix tests on 32-bit
  test/show.jl
Labels: CI

#3352 Prepare for 1.6 release
  Project.toml
Labels: ecosystem

#3357 more descriptive error message for `only`
  src/abstractdataframe/abstractdataframe.jl
Labels: non-breaking

#3356 Improve error message when pushing/appending with promote=true
  src/dataframe/insertion.jl
  test/insertion.jl
Labels: non-breaking

#3362 Add vector of names method to `rename` docstring
  src/abstractdataframe/abstractdataframe.jl
Labels: doc

#3359 Bk/fix faster orderings
  NEWS.md
  Project.toml
  test/sort.jl
Labels: bug, ecosystem
