Repository JuliaData/DataFrames.jl, pull requests merged in 2023-10, with the labels that each got.

#3385 Fix `@spawn_or_run_task` with interactive threads
  .github/workflows/ci.yml
  NEWS.md
  docs/src/lib/functions.md
  src/other/utils.jl
Labels: ecosystem

#3386 add cols to mapcols and mapcols!
  NEWS.md
  src/abstractdataframe/iteration.jl
  test/iteration.jl
Labels: feature

#3393 fix nonunique bug
  NEWS.md
  src/abstractdataframe/unique.jl
  src/groupeddataframe/utils.jl
  test/duplicates.jl
  test/grouping.jl
Labels: bug

#3394 remove unnecessary @time in tests
  test/join.jl
Labels: ecosystem
