Repository JuliaData/DataFrames.jl, pull requests merged in 2023-05, with the labels that each got.

#3304 deleteat! where drop is a column
  NEWS.md
  src/dataframe/dataframe.jl
  test/dataframe.jl
Labels: bug

#3320 Allow to always pass column names in DataFrame constructor
  NEWS.md
  src/dataframe/dataframe.jl
  src/dataframerow/dataframerow.jl
  src/other/tables.jl
  test/constructors.jl
Labels: feature

#3329 Update documentation of how to disable precompilation
  docs/src/man/basics.md
Labels: doc

#3332 optimize reverse! for small data frames and factor out _foreach_unique_column
  src/abstractdataframe/abstractdataframe.jl
Labels: non-breaking

#3333 Add "Julia for Data Analysis" reference in manual
  docs/src/index.md
Labels: doc
