Repository JuliaData/DataFrames.jl, pull requests merged in 2023-01, with the labels that each got.

#3263 improve error message in operation specification syntax
  src/groupeddataframe/splitapplycombine.jl
Labels: doc

#3262 document breaking change policy
  docs/src/index.md
Labels: doc

#3245 add support for Tables.AbstractRow in push!, pushfirst!, and insert!
  NEWS.md
  src/dataframe/insertion.jl
  test/insertion.jl
Labels: feature

#3264 Fix bug in subset[!] when handling no conditions case
  NEWS.md
  src/abstractdataframe/subset.jl
  test/subset.jl
Labels: bug

#3268 Fix error in fast aggregation of missing only columns for sum and mean
  NEWS.md
  src/abstractdataframe/selectionfast.jl
  test/select.jl
Labels: bug

#3271 Update TagBot.yml
  .github/workflows/TagBot.yml
Labels: CI

#3269 add information about TableMetadaTools.jl to docs
  docs/src/index.md
  docs/src/lib/metadata.md
Labels: doc

#3273 correctly index into a SubDataFrame with no columns
  NEWS.md
  src/subdataframe/subdataframe.jl
  test/subdataframe.jl
Labels: bug

#3256 Improve performance of dropmissing
  docs/src/lib/functions.md
  src/abstractdataframe/abstractdataframe.jl
  test/data.jl
Labels: performance

#3276 Improve allcombinations docstring + minor cleanups after #3256
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  src/dataframe/dataframe.jl
  test/data.jl
Labels: bug, doc

#3260 add keep to nonunique, unique, and unique!
  NEWS.md
  src/DataFrames.jl
  src/abstractdataframe/abstractdataframe.jl
  src/abstractdataframe/unique.jl
  src/groupeddataframe/groupeddataframe.jl
  src/groupeddataframe/utils.jl
  test/data.jl
  test/duplicates.jl
Labels: feature
