Repository JuliaData/DataFrames.jl, pull requests merged in 2023-06, with the labels that each got.

#3310 add init kwarg to vcat
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  test/dataframe.jl
Labels: feature

#3341 Add test for issue #3340 which exposed upstream issues with the use of TimSort
  test/sort.jl
Labels: ecosystem

#3312 Simple uniqueness checks for sorting-related functions
  NEWS.md
  src/abstractdataframe/sort.jl
  test/sort.jl
Labels: feature

#3342 fix dispatch errors in tests on Julia 1.10
  test/grouping.jl
  test/select.jl
Labels: ecosystem

#3347 Do not crop columns with type Base.UUID
  src/abstractdataframe/show.jl
  test/show.jl
Labels: display

#3344 improve unstack error messages
  src/abstractdataframe/reshape.jl
  test/reshape.jl
Labels: non-breaking

#3349 improve error messages in joins
  docs/src/man/joins.md
  src/join/composer.jl
Labels: feature
