Repository JuliaData/DataFrames.jl, pull requests merged in 2024-09, with the labels that each got.

#3459 Remove REPL dependency
  Project.toml
  src/DataFrames.jl
  src/other/index.jl
Labels: ecosystem

#3447 Add TidierData to frameworks docs page
  docs/Project.toml
  docs/src/man/querying_frameworks.md
Labels: doc

#3463 fix tests on nightly and 32-bit
  src/groupeddataframe/complextransforms.jl
  test/io.jl
  test/select.jl
Labels: bug

#3448 add `?` suffix to show on all return paths
  src/abstractdataframe/show.jl
Labels: bug, display

#3464 Improve names docs
  src/abstractdataframe/abstractdataframe.jl
Labels: doc

#3433 Advanced transformation examples
  docs/src/man/working_with_dataframes.md
Labels: doc
