Repository JuliaData/DataFrames.jl, pull requests merged in 2024-01, with the labels that each got.

#3413 Fix eachrow and eachcol indexing with CartesianIndex
  NEWS.md
  src/abstractdataframe/iteration.jl
  test/iteration.jl
Labels: bug

#3416 Update for Documenter.jl v1 and Julia v1.10
  docs/Project.toml
  docs/make.jl
  docs/src/man/getting_started.md
  src/abstractdataframe/iteration.jl
Labels: doc

#3419 Change big to BigInt calls
  NEWS.md
  src/abstractdataframe/abstractdataframe.jl
  src/dataframe/dataframe.jl
  src/groupeddataframe/utils.jl
  src/join/core.jl
Labels: bug

#3422 Import groupby from DataAPI, remove by and aggregate
  NEWS.md
  Project.toml
  src/DataFrames.jl
  src/deprecated.jl
  test/deprecated.jl
Labels: ecosystem
